# deploy/kubernetes/secrets.yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault
  namespace: production
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    keyvaultName: "azure-go-app-kv-prod"
    objects: |
      array:
        - |
          objectName: DB-PASSWORD
          objectType: secret
          objectVersion: ""
        - |
          objectName: REDIS-CONNECTION
          objectType: secret
          objectVersion: ""
    tenantId: "${TENANT_ID}"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: azure-go-app-sa
  namespace: production
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: azure-go-app-id-binding
  namespace: production
spec:
  azureIdentity: azure-go-app-identity
  selector: azure-go-app-identity
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: azure-go-app-identity
  namespace: production
spec:
  type: 0
  resourceID: /subscriptions/${SUBSCRIPTION_ID}/resourcegroups/azure-go-app-prod-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/azure-go-app-identity
  clientID: ${CLIENT_ID}